### ISSUE TITLE
Error creating stack

### ISSUE THREAD

**Issue by vikashvverma** [scarolan/vault-aws-cf#3]
The stack creation fails because it's not able to find was AMI for vault and consul
<img width="1160" alt="Screenshot 2020-05-13 at 3 30 01 PM" src="https://user-images.githubusercontent.com/915277/81799316-cd159780-952e-11ea-8f67-5e87a39bbd89.png">

**Comment by amitoj9** [comment]
Facing same with with creating of stack

**Comment by opsrom** [comment]
remember to modify the AMIs used in the YAML file (at the beginning) with the IDs of the AMIs created via Packer

**Comment by scarolan** [comment]
You need to create your own packer AMIs.  I'm not sure HashiCorp provides pre-built ones yet.
