### ISSUE TITLE
Integrated storage option?

### ISSUE THREAD

**Issue by amcginlay** [scarolan/vault-aws-cf#8]
Hi Sean (and contributors),

In [your presentation](https://www.youtube.com/watch?v=0K1b1mT6t8E) (great work BTW) you mention an "integrated storage option". It sounds like this would eliminate the need for Consul and reduce the VM count which would be useful to me.

Is there some (non-prod) version of your CF (or Terraform) template available which delivers on this?
Alternatively, if you could point me in the right direction, that'll be great. Thx.

**Comment by scarolan** [comment]
Hy @amcginlay  - sorry for the (super) slow response - i don't check github notifications often.

The code in this repo is really old and very likely outdated.  Integrated storage has been the default for new vault installation for a while.  You no longer need to configure your own raft (consul) storage in almost all use cases.  I'd ping the folks at Hashicorp and ask them if they have a newer cloudformation template for deploying Vault on AWS.
